import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import projectsRouter from "./projects.js";
import workflowsRouter from "./workflows.js";
import deploymentsRouter from "./deployments.js";
import modelsRouter from "./models.js";
import activityRouter from "./activity.js";
import dashboardRouter from "./dashboard.js";
import aiRouter from "./ai.js";
import conversationsRouter from "./conversations.js";
import versionsRouter from "./versions.js";
import checklistRouter from "./checklist.js";
import usageRouter from "./usage.js";
import notificationsRouter from "./notifications.js";
import agentRouter from "./agent.js";
import subscriptionRouter from "./subscription.js";
import eventsRouter from "./events.js";
import builderRouter from "./builder.js";

const router: IRouter = Router();

router.use(eventsRouter);
router.use(builderRouter);
router.use(healthRouter);
router.use(projectsRouter);
router.use(workflowsRouter);
router.use(deploymentsRouter);
router.use(modelsRouter);
router.use(activityRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(conversationsRouter);
router.use(versionsRouter);
router.use(checklistRouter);
router.use(usageRouter);
router.use(notificationsRouter);
router.use(agentRouter);
router.use(subscriptionRouter);

export default router;
